FROM arm32v6/debian:bookworm

# Add environment variables to force the ARMv6 CPU architecture
ENV CFLAGS="-march=armv6zk -mcpu=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard"
ENV CXXFLAGS="-march=armv6zk -mcpu=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard"
ENV PYTHON_VERSION=3.11.9

# Add the specific system headers for dbus and other pwnagotchi essentials
RUN apt update && apt install -y --no-install-recommends\
    python3-pip python3-dev python3-wheel build-essential git libssl-dev libfreetype6-dev\
    libdbus-1-dev libglib2.0-dev m4 libyaml-dev libatomic-ops-dev libswscale-dev\
    libjpeg-dev libpng-dev zlib1g-dev pkg-config libavcodec-dev libavformat-dev\
    gfortran libopenblas-dev liblapack-dev cmake ninja-build libatomic1\
    && rm -rf /var/lib/apt/lists/*

# Compile Python 3.11 with max optimizations
RUN wget https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz \
    && tar xzf Python-$PYTHON_VERSION.tgz \
    && cd Python-$PYTHON_VERSION \
    && ./configure --prefix=/usr/local --enable-optimizations --with-lto \
    && make -j$(nproc) \
    && make altinstall \
    && cd .. \
    && rm -rf Python-$PYTHON_VERSION*

# Pre-install the build system tools to avoid isolation issues
RUN export PIP_BREAK_SYSTEM_PACKAGES=1 && \
    python3 -m pip install --upgrade pip setuptools wheel && \
    python3 -m pip install meson-python meson ninja